language: rust
rust:
  - stable
    #  - nightly
    #jobs:
    #  allow_failures:
    #    - rust: nightly
    #  fast_finish: true
cache: cargo
os:
  - linux
  - windows
git:
  depth: 3

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./.travis/codecov.sh; fi
