[package]
name = "game"
version = "0.1.0"
authors = ["Antoni Simka <antonisimka.8@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
anyhow = "1.0.32"

# Graphics
wgpu = "0.6.0"
winit = { version = "0.23.0", default_features = false, features = ["x11"] }
futures = { version = "0.3" }

# Math
nalgebra = "0.20.0"

# Physics
ncollide3d = "0.22.0" 

# Texture loading
image = "0.19.0"

# Other
env_logger = "0.7.1"
log = "*"

# Data loading
bytemuck = { version = "1.4.1", features = ["derive"] }

# OBJ model loading
wavefront_obj = "8.0.0"

# Misc
#flatbuffers = "0.6.0"
floating-duration = "0.1.2"

[dependencies.legion]
version = "0.3.1"
features = ["extended-tuple-impls"]

[build-dependencies]
# Used for copying the assets dir to the target dir for testing
walkdir = "2.1"

