[package]
name = "game"
version = "0.1.0"
authors = ["Antoni Simka <antonisimka.8@gmail.com>"]
build = "build.rs"

[dependencies]
gl = { path = "lib/gl" }
failure = "0.1"
render_gl_derive = { path = "render_gl_derive" }
vec-2-10-10-10 = "0.1.2"
half = "1.4.0"
nalgebra = "0.19.0"
ncollide3d = "0.21.0"
nphysics3d = "0.13.1"
image = "0.19.0"
tobj = "0.1.11"
floating-duration = "0.1.2"
flatbuffers = "0.6.0"

[dependencies.sdl2]
version = "0.32.2"
features = ["bundled", "static-link"]

[build-dependencies]
walkdir = "2.1"

[features]
gl_debug = ["gl/debug"]
