[package]
name = "game"
version = "0.1.0"
authors = ["Antoni Simka <antonisimka.8@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
# TODO: Failure is deprecated, replace it
# failure = "0.1.8"
anyhow = "1.0.32"

# Graphics
# TODO: Transition to gfx-rs or wgpu
gl = { path = "lib/gl" }
render_gl_derive = { path = "lib/render_gl_derive" }
vec-2-10-10-10 = "0.1.2"
half = "1.4.0"

# Physics
# TODO: Transition to own physics engine or Rapier
nalgebra = "0.19.0"
ncollide3d = "0.21.0"
nphysics3d = "0.13.1"

# No idea what those are for
image = "0.19.0"
tobj = "0.1.11"
floating-duration = "0.1.2"
legion = "0.3.1"
thiserror = "1.0.20"

#flatbuffers = "0.6.0"

[dependencies.sdl2]
version = "0.32.2"
#features = ["bundled", "static-link"]

[build-dependencies]
# Used for copying the assets dir to the target dir for testing
walkdir = "2.1"
