[package]
name = "game"
version = "0.1.0"
authors = ["Antoni Simka <antonisimka.8@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
# TODO: Failure is deprecated, replace it
# failure = "0.1.8"
anyhow = "1.0.32"

# Graphics
# TODO: Transition to gfx-rs or wgpu [IN PROGRESS]
wgpu = "0.6.0"
winit = { version = "0.23.0", default_features = false, features = ["x11"] }
futures = { version = "0.3" }

#gl = { path = "lib/gl" }
#render_gl_derive = { path = "lib/render_gl_derive" }
#vec-2-10-10-10 = "0.1.2"
#half = "1.4.0"

# Physics
nalgebra = "0.20.0"
ncollide3d = "0.22.0" 
# Texture loading
image = "0.19.0"

# OBJ model loading
#tobj = "0.1.11"
floating-duration = "0.1.2"
#thiserror = "1.0.20"

# Other
env_logger = "0.7.1"
log = "*"

# Data loading
bytemuck = { version = "1.4.1", features = ["derive"] }
wavefront_obj = "8.0.0"

#flatbuffers = "0.6.0"

[dependencies.legion]
version = "0.3.1"
features = ["extended-tuple-impls"]

#[dependencies.sdl2]
#version = "0.34.3"
#features = ["bundled", "static-link"]

[build-dependencies]
# Used for copying the assets dir to the target dir for testing
walkdir = "2.1"
