[package]
name = "render_gl_derive"
version = "0.1.0"
authors = ["Skelebot <antonisimka.8@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "0.3.11"
syn = "0.11.11"

[lib]
proc-macro = true
